// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/taskflow/Dashboard.tsx": () => import("../components/mockups/taskflow/Dashboard.tsx"),
  "./components/mockups/taskflow/Login.tsx": () => import("../components/mockups/taskflow/Login.tsx")
};
